# Generated by Django 5.2.1 on 2025-06-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TinyURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True)),
                (
                    "short_code",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
            ],
        ),
    ]
