services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: smallurl_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/smallurl
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:17.5
    ports:
      - "5432:5432"
    volumes:
      - smallurl-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
volumes:
  smallurl-data:
